### ISSUE TITLE
DB変更に伴う`/search`の変更

### ISSUE THREAD

**Issue by suzakutakumi** [yuorei/lost-item-backend#39]
#38 終了後
最初に、[Notion](https://www.notion.so/API-dd98058817d2487ca81acf8821429d6c)を書き換えます。
なるべく、次にそれをチーム内で確認を貰う。
その後、プログラムを書き換える。

**Comment by yuorei** [comment]
https://github.com/yuorei/lost-item-backend/pull/46
実装完了
